import test from "node:test";
import assert from "node:assert/strict";
import { setupPage } from "../src/setup-ui.mjs";

test("renders the guided setup dashboard without embedded secrets", () => {
  const html = setupPage();
  assert.match(html, /MovieBoxPro & Nuvio Hub/);
  assert.match(html, /Profile & Multi-Device Manager/);
  assert.match(html, /id="profileSelect"/);
  assert.match(html, /Stream Activity & Cache Analytics/);
  assert.match(html, /id="statAvgTime"/);
  assert.match(html, /Open Login Window/);
  assert.match(html, /Reveal Provider URL/);
  assert.match(html, /Nuvio Cloud Sync/);
  assert.match(html, /Timezone & Calendar/);
  assert.match(html, /id="userTimezone"/);
  assert.match(html, /Recommendation Seeds \(Unlimited\)/);
  assert.match(html, /Create Custom Feed/);
  assert.match(html, /id="customFeedBuilder"/);
  assert.match(html, /Backup & System Restore/);
  assert.match(html, /id="downloadBackupBtn"/);
  assert.match(html, /api\/setup\/catalog-url/);
  assert.match(html, /document\.execCommand\('copy'\)/);
  assert.match(html, /link rel="manifest" href="\/app\.webmanifest"/);
  assert.match(html, /meta name="apple-mobile-web-app-capable"/);
  assert.match(html, /id="updateBanner"/);
  assert.match(html, /Lock Dashboard Session/);
  assert.doesNotMatch(html, /COMPANION_KEY=/);
  assert.doesNotMatch(html, /PLUGIN_SETUP_KEY=/);
  assert.doesNotMatch(html, /TMDB_API_KEY=/);
});
