export function setupPage() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <title>MovieBoxPro Companion Setup</title>
  <style>
    :root{color-scheme:dark;--bg:#080c18;--panel:#11182a;--panel2:#17213a;--line:#283653;--text:#f3f6ff;--muted:#9eabc5;--accent:#7c9cff;--good:#49d49d;--bad:#ff7387;--warn:#ffc66d}
    *{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at 10% 0,#172347 0,transparent 35%),var(--bg);color:var(--text);font:15px/1.5 ui-sans-serif,system-ui,-apple-system,sans-serif;min-height:100vh}
    main{width:min(980px,calc(100% - 28px));margin:auto;padding:42px 0 70px}.hero{display:flex;justify-content:space-between;gap:24px;align-items:flex-start;margin-bottom:28px}.eyebrow{color:var(--accent);font-weight:750;letter-spacing:.08em;text-transform:uppercase;font-size:12px}h1{font-size:clamp(28px,5vw,46px);line-height:1.08;margin:8px 0 10px;letter-spacing:-.035em}.lead{color:var(--muted);max-width:650px;margin:0}.badge{padding:7px 11px;border:1px solid var(--line);background:#0e1528;border-radius:999px;color:var(--muted);white-space:nowrap}
    .grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:16px}.card{background:linear-gradient(145deg,var(--panel),#0d1425);border:1px solid var(--line);border-radius:18px;padding:20px;box-shadow:0 18px 50px #0004}.wide{grid-column:1/-1}.card h2{font-size:18px;margin:0 0 5px}.card p{color:var(--muted);margin:0 0 16px}.row{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.status{display:inline-flex;gap:8px;align-items:center;color:var(--muted)}.dot{width:9px;height:9px;border-radius:50%;background:var(--warn);box-shadow:0 0 16px currentColor}.dot.good{background:var(--good)}.dot.bad{background:var(--bad)}
    button,a.button{appearance:none;border:1px solid #405a98;background:#20345f;color:white;padding:10px 14px;border-radius:10px;font-weight:700;text-decoration:none;cursor:pointer}button.secondary,a.secondary{background:transparent;border-color:var(--line);color:var(--text)}button:disabled{opacity:.5;cursor:wait}label{display:block;color:var(--muted);font-size:13px;margin:12px 0 5px}input,textarea{width:100%;padding:11px 12px;border-radius:10px;border:1px solid var(--line);background:#091020;color:var(--text);font:inherit}textarea{resize:vertical}code,.code{font-family:ui-monospace,SFMono-Regular,monospace;font-size:12px;overflow-wrap:anywhere;background:#091020;border:1px solid var(--line);border-radius:10px;padding:11px;display:block;color:#dce5ff}.message{min-height:24px;color:var(--muted);margin-top:10px}.message.error{color:var(--bad)}.message.ok{color:var(--good)}ol{color:var(--muted);padding-left:20px}strong{color:var(--text)}footer{color:var(--muted);font-size:12px;margin-top:18px;text-align:center}
    @media(max-width:720px){main{padding-top:24px}.hero{display:block}.badge{display:inline-block;margin-top:14px}.grid{grid-template-columns:1fr}.wide{grid-column:auto}}
  </style>
</head>
<body><main>
  <section class="hero"><div><div class="eyebrow">Local account bridge</div><h1>MovieBoxPro Companion</h1><p class="lead">Configure the private bridge, connect your MovieBoxPro browser session, and install the provider in Nuvio. Credentials remain on this host.</p></div><div class="badge" id="serviceBadge">Loading…</div></section>
  <section class="grid">
    <article class="card"><h2>1. Companion</h2><p>Confirm the service and Nuvio-facing address.</p><div class="status"><span class="dot" id="serviceDot"></span><span id="serviceText">Checking service</span></div><label for="publicUrl">Nuvio-facing URL</label><input id="publicUrl" autocomplete="off" placeholder="http://192.168.1.20:43110"><div class="row" style="margin-top:12px"><button id="saveUrl">Save address</button></div><div class="message" id="configMessage"></div></article>
    <article class="card"><h2>2. TMDb metadata</h2><p>Used only by the companion to match Nuvio titles.</p><div class="status"><span class="dot" id="tmdbDot"></span><span id="tmdbText">Checking configuration</span></div><label for="tmdbKey">TMDb v3 API key</label><input id="tmdbKey" type="password" autocomplete="new-password" placeholder="Leave blank to keep the saved key"><div class="row" style="margin-top:12px"><button id="saveTmdb">Save key</button></div><div class="message" id="tmdbMessage"></div></article>
    <article class="card"><h2>3. MovieBoxPro login</h2><p>Uses a dedicated persistent Chromium profile. The dashboard never reads or displays cookies.</p><div class="status"><span class="dot" id="movieboxDot"></span><span id="movieboxText">Not checked</span></div><div class="row" style="margin-top:14px"><button id="openLogin">Open login window</button><button class="secondary" id="checkLogin">Check status</button><a class="button secondary" id="novnc" target="_blank" rel="noreferrer" hidden>Open server desktop</a></div><div class="message" id="loginMessage"></div></article>
    <article class="card"><h2>4. Install in Nuvio</h2><p>Reveal the protected local manifest only when you are ready to add it to your Nuvio account.</p><div class="row"><button id="revealPlugin">Reveal installation URL</button><button class="secondary" id="copyPlugin" hidden>Copy</button></div><textarea id="pluginUrl" class="code" rows="3" readonly style="display:none;margin-top:12px" aria-label="Private Nuvio installation URL"></textarea><div class="message" id="pluginMessage"></div></article>
    <article class="card wide"><h2>5. Temporary TV calendar catalogs</h2><p>Add shows you like to personalize recommendations, then install this separately under Nuvio Web → Add-ons.</p><label for="seedShows">Shows you like (commas or new lines)</label><textarea id="seedShows" rows="3" placeholder="King of the Hill, The Simpsons, Bob's Burgers"></textarea><div class="row" style="margin-top:12px"><button id="saveSeeds">Save shows</button><button class="secondary" id="revealCatalog">Reveal catalog URL</button><button class="secondary" id="copyCatalog" hidden>Copy</button></div><textarea id="catalogUrl" class="code" rows="3" readonly style="display:none;margin-top:12px" aria-label="Private Nuvio catalog URL"></textarea><div class="message" id="catalogMessage"></div></article>
    <article class="card wide"><h2>Finish on each device</h2><ol><li>Add the provider URL under <strong>Nuvio Web → Plugins</strong>.</li><li>Add the calendar URL under <strong>Nuvio Web → Add-ons</strong>.</li><li>Refresh, then fully restart Nuvio on Android TV.</li><li>Remove only the calendar add-on after Nuvio gains the native Calendar page.</li></ol><div class="row"><button class="secondary" id="logout">Lock dashboard</button></div></article>
  </section><footer>Unofficial interoperability tool for your own authorized account. Never expose this dashboard or port 43110 to the public internet.</footer>
</main><script>
  const q=(id)=>document.getElementById(id); let pluginValue='',catalogValue='';
  function msg(id,text,type=''){q(id).textContent=text;q(id).className='message '+type}
  function dot(id,state){q(id).className='dot '+(state===true?'good':state===false?'bad':'')}
  async function copyText(value,fieldId='pluginUrl'){
    if(navigator.clipboard&&navigator.clipboard.writeText){try{await navigator.clipboard.writeText(value);return}catch{}}
    const field=q(fieldId);field.focus();field.select();field.setSelectionRange(0,value.length);
    if(!document.execCommand||!document.execCommand('copy'))throw new Error('Copy unavailable');
  }
  async function api(path,options={}){const r=await fetch(path,{...options,headers:{'Content-Type':'application/json',...(options.headers||{})}});const d=r.status===204?{}:await r.json();if(!r.ok)throw new Error(d.error||('Request failed: '+r.status));return d}
  async function load(){try{const s=await api('/api/setup/state');q('serviceBadge').textContent='Service online';q('serviceText').textContent=s.host+':'+s.port;dot('serviceDot',true);q('publicUrl').value=s.publicUrl;dot('tmdbDot',s.tmdbConfigured);q('tmdbText').textContent=s.tmdbConfigured?'Key saved':'Key required';q('seedShows').value=(s.recommendationSeeds||[]).map(x=>x.name).join(', ');if(s.docker){q('novnc').hidden=false;q('novnc').href=s.noVncUrl}}catch(e){q('serviceBadge').textContent='Service unavailable';dot('serviceDot',false)}}
  q('saveUrl').onclick=async()=>{try{await api('/api/setup/config',{method:'POST',body:JSON.stringify({publicUrl:q('publicUrl').value})});msg('configMessage','Address saved.','ok')}catch(e){msg('configMessage',e.message,'error')}};
  q('saveTmdb').onclick=async()=>{try{await api('/api/setup/config',{method:'POST',body:JSON.stringify({tmdbApiKey:q('tmdbKey').value})});q('tmdbKey').value='';dot('tmdbDot',true);q('tmdbText').textContent='Key saved';msg('tmdbMessage','TMDb key saved without displaying it.','ok')}catch(e){msg('tmdbMessage',e.message,'error')}};
  q('openLogin').onclick=async()=>{try{q('openLogin').disabled=true;await api('/api/setup/login',{method:'POST'});msg('loginMessage','Login window opened. Complete the code login there, then check status.','ok')}catch(e){msg('loginMessage',e.message,'error')}finally{q('openLogin').disabled=false}};
  q('checkLogin').onclick=async()=>{try{q('checkLogin').disabled=true;const s=await api('/api/setup/moviebox-status');dot('movieboxDot',s.authenticated);q('movieboxText').textContent=s.authenticated?'Authenticated':'Login required';msg('loginMessage',s.authenticated?'MovieBoxPro session is ready.':'Complete login and check again.',s.authenticated?'ok':'error')}catch(e){dot('movieboxDot',false);msg('loginMessage',e.message,'error')}finally{q('checkLogin').disabled=false}};
  q('revealPlugin').onclick=async()=>{try{const d=await api('/api/setup/plugin-url');pluginValue=d.url;q('pluginUrl').value=d.url;q('pluginUrl').style.display='block';q('copyPlugin').hidden=false;msg('pluginMessage','Treat this URL like a password.','')}catch(e){msg('pluginMessage',e.message,'error')}};
  q('copyPlugin').onclick=async()=>{try{await copyText(pluginValue);msg('pluginMessage','Copied.','ok')}catch{q('pluginUrl').focus();q('pluginUrl').select();msg('pluginMessage','Automatic copy is blocked. The complete URL is selected; use your browser copy command.','error')}};
  q('saveSeeds').onclick=async()=>{try{q('saveSeeds').disabled=true;const d=await api('/api/setup/recommendations',{method:'POST',body:JSON.stringify({shows:q('seedShows').value})});q('seedShows').value=d.seeds.map(x=>x.name).join(', ');msg('catalogMessage','Saved '+d.seeds.length+' recommendation shows.','ok')}catch(e){msg('catalogMessage',e.message,'error')}finally{q('saveSeeds').disabled=false}};
  q('revealCatalog').onclick=async()=>{try{const d=await api('/api/setup/catalog-url');catalogValue=d.url;q('catalogUrl').value=d.url;q('catalogUrl').style.display='block';q('copyCatalog').hidden=false;msg('catalogMessage','Add this URL under Nuvio Add-ons. Treat it like a password.','')}catch(e){msg('catalogMessage',e.message,'error')}};
  q('copyCatalog').onclick=async()=>{try{await copyText(catalogValue,'catalogUrl');msg('catalogMessage','Copied.','ok')}catch{q('catalogUrl').focus();q('catalogUrl').select();msg('catalogMessage','Automatic copy is blocked. The complete URL is selected.','error')}};
  q('logout').onclick=async()=>{await api('/api/setup/logout',{method:'POST'});location.reload()};load();
</script></body></html>`;
}
